### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by fturmel**
Not sure if you were accepting PRs on this project, but I was evaluating it and did stumble on a few things that I thought I would contribute back.

Commit descriptions are pretty explicit, but I do want to call out 79c7d6f5c2ab9029da22589a3fd319f7f6efae6e which is a "fix" that ends up changing the sequence output of `nextChar`, `nextString` and `nextArrayItem` so probably warrants a major version change.

### CODE REVIEW

**Comment by zeh** [comment]
Oh sh*t Francis! I haven't seen this one before! Not sure why I have notifications disabled...

I'll take a look at those.

Hope all is well!

**Comment by zeh** [comment]
Ok, these are great. The extraneous recalculate() calls are baffling. I think at some point I replaced `_value` with the `nextInt()` call and forgot to remove that.

I'll merge it and do a few additional changes before releasing a new major version.

Thanks again!

**Comment by fturmel** [comment]
Glad that was helpful! It's a great library, no surprise here coming from you.

I also converted p5.js's random lib to TypeScript at the same time I sent this PR, but in the end I didn't even use a PRNG to solve my project's issue. I am not a clever man.

Miss ya! We should catch up soon.

**Comment by zeh** [comment]
I guess sometimes the journey is the destination. I spend dozens of hours on things I never end up using. This whole package is a good example: I build it because I needed a fast, deterministic, simple RNG for a specific feature on my website... and that feature was removed a couple of months ago. Ah well. I still use it from time to time just because it's tiny and predictable, so all good!

The updated package is now published as ~[v6.0.0](https://github.com/zeh/prando/releases/tag/v6.0.0)~ [v6.0.1](https://github.com/zeh/prando/releases/tag/v6.0.1). I just did some additional updates to remove TSLint and update all other build dependencies. Thanks again!

On a side note, I think I've also finally fixed notifications from this project. I was reading old issues and they all begin with me replying "oh I'm sorry I didn't see this soon!" months after the fact... 😅

Miss you too, man. I still hope we can go to Montreal this 4th of July as we had been doing every year before 2020... we'll see.

**Pull request merged**
